server:
  port: 88
spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://gmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://gmall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://gmall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://gmall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: tool_route
          uri: lb://gmall-tool
          predicates:
            - Path=/api/tool/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://gmall-admin
          # 请求断言
          predicates:
            - Path=/api/**
          filters:
            # RewritePath路径重写
            - RewritePath=/api/(?<segment>.*),/gmall-admin/$\{segment}

        - id: product_host_route
          uri: lb://gmall-product
          predicates:
            - Host=gxmall.com,item.gxmall.com

        - id: search_host_route
          uri: lb://gmall-search
          predicates:
            - Host=search.gxmall.com

        - id: auth_host_route
          uri: lb://gmall-auth
          predicates:
            - Host=auth.gxmall.com

        - id: cart_host_route
          uri: lb://gmall-cart
          predicates:
            - Host=cart.gxmall.com

        - id: order_host_route
          uri: lb://gmall-order
          predicates:
            - Host=order.gxmall.com